// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Mxg65fJYMHJkMSHZkKiFuz4AaSoA1Es',
    appId: '1:858399038228:web:d70e6755001573ea9f8001',
    messagingSenderId: '858399038228',
    projectId: 'todoapp-dafef',
    authDomain: 'todoapp-dafef.firebaseapp.com',
    storageBucket: 'todoapp-dafef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijm5iHucN6CrYyScOOnCBXKJaGxStBA4',
    appId: '1:858399038228:android:96bedb8a323682e99f8001',
    messagingSenderId: '858399038228',
    projectId: 'todoapp-dafef',
    storageBucket: 'todoapp-dafef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1S5q1CpodqPWTWMqwFzNnSYFJ7CUfSMQ',
    appId: '1:858399038228:ios:05be1866258867799f8001',
    messagingSenderId: '858399038228',
    projectId: 'todoapp-dafef',
    storageBucket: 'todoapp-dafef.appspot.com',
    iosClientId: '858399038228-eaqfr3smg730ue15rtqnp0vc4bjsn0h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1S5q1CpodqPWTWMqwFzNnSYFJ7CUfSMQ',
    appId: '1:858399038228:ios:05be1866258867799f8001',
    messagingSenderId: '858399038228',
    projectId: 'todoapp-dafef',
    storageBucket: 'todoapp-dafef.appspot.com',
    iosClientId: '858399038228-eaqfr3smg730ue15rtqnp0vc4bjsn0h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
